### ISSUE TITLE
Android 5.0.1 Mobile

### ISSUE THREAD

**Issue by jazdown** [charlie-quinn/portfolio#11]
I really want to click your arrow to go down, but the way the android default browser is, I can't do it. Maybe if you can push your button up like 20px it would be clickable. (I try but I click on the browser home button)
![screenshot_2015-10-08-08-40-50](https://cloud.githubusercontent.com/assets/6373208/10367421/6a4036ea-6d9e-11e5-81b9-939bd82c1456.png)

**Comment by charlie-quinn** [comment]
@jazdown I think I fixed it?

**Comment by jazdown** [comment]
Very close, dont worry if you dont want to move it up more
