### ISSUE TITLE
Re: lightbox issue discussed on Canvas

### ISSUE THREAD

**Issue by thomasjbradley** [charlie-quinn/portfolio#15]
Here's what I'm seeing in Firefox (most recent version):

![screen shot 2015-11-02 at 3 05 05 pm](https://cloud.githubusercontent.com/assets/105192/10892744/33dfcc1c-8173-11e5-9134-6f7ddff64c5b.png)

Notice how the last few words are cut off and I can't seem to get to them.

---

Looks like you've got the close button on top of the navigation now though.

**Comment by charlie-quinn** [comment]
Thank you! Text now has a margin-bottom :)
