### ISSUE TITLE
Some questionable things happening in safari 8

### ISSUE THREAD

**Issue by dagerebe** [charlie-quinn/portfolio#3]
I'm just making sure you know these things are happening.
<img width="796" alt="screen shot 2015-10-08 at 9 00 06 am" src="https://cloud.githubusercontent.com/assets/6340285/10366868/31fdd5ec-6d9b-11e5-8d17-e000f74f8ab6.png">
<img width="490" alt="screen shot 2015-10-08 at 9 00 17 am" src="https://cloud.githubusercontent.com/assets/6340285/10366869/31fe2b8c-6d9b-11e5-809e-6eb56b7fdefd.png">

**Comment by charlie-quinn** [comment]
Thanks @dagerebe I think I resolved the issue! :)
