### ISSUE TITLE
Voiceover Testing

### ISSUE THREAD

**Issue by emilylavinskas** [charlie-quinn/portfolio#6]
Overall, it read everything well! My only advice is to make sure that the social media links say what they're linking to because right now they're reading back just as the usernames, and not WHERE they link to. As well, just make sure that all of your portfolio pieces have alts added to them when they are input because it's skipping over all of the placeholders as it currently is. :)

**Comment by charlie-quinn** [comment]
Thanks @emilylavinskas :)
