### ISSUE TITLE
Firefox on Nexus 4: link to id

### ISSUE THREAD

**Issue by kayleemenard** [charlie-quinn/portfolio#8]
Perhaps adding margin to the work section or h2 would prevent the sticky nav from overlapping your h2 in both portrait and landscape?

![tmp_941-screenshot_2015-10-08-09-09-431549844945](https://cloud.githubusercontent.com/assets/6373202/10367317/b6e7b8f2-6d9d-11e5-8bc8-d36e04fa9d8e.png)

**Comment by charlie-quinn** [comment]
Hey @kayleemenard I removed my H2 from the work section (since the nav is fixed, the H2 is a bit redundant). Let me know what you think!
