### ISSUE TITLE
Firefox Testing  

### ISSUE THREAD

**Issue by paisley-laurenzio** [charlie-quinn/portfolio#9]
A few comments. The placement of the text on the banner image of you covers your face when I scale the site making it unreadable. I think it was really cool when your face was cut off halfway on the edge of the screen. Maybe you could try keeping it like that as the site scale up? This could fix the issue with the text overlapping the face. 
![screen shot 2015-10-08 at 9 19 39 am](https://cloud.githubusercontent.com/assets/6371044/10367321/b9021a24-6d9d-11e5-9740-feae0a4e6028.png)

Maybe consider using a different colour on the small screen for the banner text so that it can still be read when it over laps the image. 
![screen shot 2015-10-08 at 9 21 25 am](https://cloud.githubusercontent.com/assets/6371044/10367365/0efabe40-6d9e-11e5-8269-9be234fc7309.png)

**Comment by charlie-quinn** [comment]
Thanks @paisley-laurenzio :)
